services:
  - type: web
    name: medme-voice-agent-prototype
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ENABLE_DATA_STORAGE
        value: "true"
      - key: GOOGLE_SHEETS_SPREADSHEET_ID
        value: "1ntiLdxQNFQDNqMCxyijxw6MCwEmnQX9HiOp7j1u57lI"
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: WEBHOOK_SECRET
        sync: false 